# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    # Install dependencies
    - name: Install dependencies
      run: npm i

    # Lint
    - name: Linting our app
      run: npm run lint

    # Test
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Test and coverage
      run: npm run test-headless

    # Sonar Cloud
    - name: SonarCloud Scan
      if: success() || failure()
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # Build node
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # Sync capacitor
    - run: npx cap sync
    - run: npm i
    - run: npm run build --if-present --prod